name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no u807263449@153.92.11.164 "cd ~/home/u807263449/domains/woosookbbq.com/public_html/admin && git pull origin main && composer install --no-dev && php artisan migrate --force"
