name: Woosoo Admin Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # PHP setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          extensions: mbstring, bcmath, intl, mysql

      # Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Create bootstrap/cache BEFORE composer install
      - name: Ensure bootstrap/cache exists
        run: |
          mkdir -p bootstrap/cache
          chmod -R 775 bootstrap/cache


      # Install composer deps
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
        

      # Install npm deps & build assets
      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      # Copy CI environment file
      - name: Setup environment
        run: cp .env.ci .env

      # Optimize Laravel
      - name: Optimize Laravel
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
